version: '3.3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - /salary-app-workspace/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: salaryapp
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always